# BERT Text Classifier

**Course:** Natural Language Processing · Unit 5 — Classification and Evaluation  
**Institution:** Universidad Tecnológica de Bolívar  
**Reference:** Jurafsky, D. & Martin, J. H. (2025). *Speech and Language Processing* (3rd ed.), Ch. 11 — Fine-Tuning and Masked Language Models  
**Python compatibility:** 3.10 · 3.11 · 3.12 · 3.13

---

In [2]:
import transformers
print(transformers.__version__)
#!pip install transformers
# pip install torch

5.17.0

> **Output interpretation:** Confirms that the Transformers library is installed and shows its version. A version ≥ 4.30 is required for the `Trainer` API and dataset integration used in this notebook.

In [ ]:
# conda install -c huggingface -c conda-forge datasets  # run once

In [ ]:
from pathlib import Path
DIR_DATA = Path.cwd() / 'data'

In [ ]:
import os
os.makedirs("./logs", exist_ok=True)
os.makedirs("./results", exist_ok=True)
os.environ["WANDB_DISABLED"] = "true"

## Step 1: Importing Libraries

In [6]:
import numpy as np
import pandas as pd
import torch
#from datasets import load_dataset
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.model_selection import train_test_split
from transformers import (
    BertForSequenceClassification,
    BertTokenizer,
    Trainer,
    TrainingArguments,
)

## Step 2: Loading and Cleaning the Dataset

In [7]:
DIR_DATA = Path.cwd() / 'data' / 'tass'
print(f'Data directory: {DIR_DATA}')

Data directory: C:\Users\epuerta\OneDrive - Universidad Tecnológica de Bolívar\Apps\courseNLP\examples\data\tass

---

## 2. The TASS 2018 Dataset

TASS is a shared-task evaluation campaign focused on Spanish-language sentiment analysis. The 2018 edition uses Twitter data with four polarity labels:

| Label | Meaning |
|---|---|
| **P** | Positive sentiment |
| **N** | Negative sentiment |
| **NEU** | Neutral (no positive or negative polarity) |
| **NONE** | Not a sentiment-bearing tweet |

## Step 3: Load Training and Test Sets

In [8]:
df_train = pd.read_csv(DIR_DATA / 'tass2018_es_train.csv', sep=',')
df_test = pd.read_csv(DIR_DATA / 'tass2018_es_test.csv', sep=',')
df_train.columns = df_train.columns.str.strip()
df_test.columns = df_test.columns.str.strip()

In [9]:
# Map the four TASS polarity labels to 0-indexed integer classes
LABEL_MAP = {'N': 0, 'NEU': 1, 'NONE': 2, 'P': 3}
ID2LABEL = {v: k for k, v in LABEL_MAP.items()}
NUM_LABELS = len(LABEL_MAP)

df_train = df_train[['content', 'sentiment/polarity/value']].dropna()
df_train['sentiment'] = df_train['sentiment/polarity/value'].map(LABEL_MAP)

df_test = df_test[['content', 'sentiment/polarity/value']].dropna()
df_test['sentiment'] = df_test['sentiment/polarity/value'].map(LABEL_MAP)

In [10]:
df_train

,content,sentiment/polarity/value,sentiment
0,-Me caes muy bien \r\n-Tienes que jugar más pa...,NONE,2
1,@myendlesshazza a. que puto mal escribo\r\n\r\...,N,0
2,@estherct209 jajajaja la tuya y la d mucha gen...,N,0
3,Quiero mogollón a @AlbaBenito99 pero sobretodo...,P,3
4,Vale he visto la tia bebiendose su regla y me ...,N,0
...,...,...,...
1003,Para mí mi mejor año fue el 2015,P,3
1004,Hoy va a ser un dia muy largo...,N,0
1005,11:11 que no me encuentre mal,NEU,1
1006,Es que son muy bonitas jo,P,3
1007,Que no jo que no soy tan irresponsable,P,3

> **Output interpretation:** Displays the cleaned dataset (1,008 tweets). The `sentiment` column now holds 0-indexed integer labels for the four TASS polarity classes (`N`=0, `NEU`=1, `NONE`=2, `P`=3), confirming that the mapping was applied correctly and no null values remain.

## Step 3: Splitting into Training and Test Sets

In [11]:
train_texts, test_texts, train_labels, test_labels = train_test_split(
    df_train['content'].tolist(),
    df_train['sentiment'].tolist(),
    test_size=0.2,
    random_state=42,
)

## Step 4: Tokenization

In [12]:
# TASS tweets are in Spanish, so we need a Spanish-pretrained BERT checkpoint
# (bert-base-uncased is English-only and would tokenize Spanish text poorly)
MODEL_NAME = 'dccuchile/bert-base-spanish-wwm-uncased'

tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)

train_encodings = tokenizer(
    train_texts, truncation=True, padding=True, max_length=128
)
test_encodings = tokenizer(
    test_texts, truncation=True, padding=True, max_length=128
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [13]:
# Tokenize the genuine TASS held-out test set (loaded from tass2018_es_test.csv)
# so the final evaluation in Step 10 is on real unseen data, not the train/val split
holdout_encodings = tokenizer(
    df_test['content'].tolist(), truncation=True, padding=True, max_length=128
)
holdout_labels = df_test['sentiment'].tolist()

In [14]:
class TassSentimentDataset(torch.utils.data.Dataset):
    """Wraps tokenizer encodings and integer labels for use with `Trainer`.

    `Trainer` expects a `Dataset` whose `__getitem__` returns a dict of
    tensors including `labels` — a raw `BatchEncoding` (what the tokenizer
    returns) has no labels attached and is not indexable the way `Trainer`
    requires.
    """

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)


train_dataset = TassSentimentDataset(train_encodings, train_labels)
val_dataset = TassSentimentDataset(test_encodings, test_labels)
holdout_dataset = TassSentimentDataset(holdout_encodings, holdout_labels)

In [15]:
vocab = tokenizer.get_vocab()
# Print the total vocabulary size
print(f"Vocabulary size: {len(vocab)}")

Vocabulary size: 31002

In [16]:
# Print the first 10 items in the vocabulary
for token, token_id in list(vocab.items())[:10]:
    print(f"{token}: {token_id}")

ivo: 14299
##idez: 6012
casera: 29086
bend: 23239
revolucionarios: 20595
responder: 5941
distinguido: 22498
difícil: 3135
marchado: 27991
[unused437]: 443

## Step 6: Defining Evaluation Metrics

In [17]:
def compute_metrics(eval_pred):
    """Compute classification metrics from model predictions.

    Args:
        eval_pred: Tuple of (logits, labels) returned by the Trainer.

    Returns:
        dict with accuracy, F1, precision, and recall (macro-averaged,
        since this is a 4-class problem: N, NEU, NONE, P).
    """
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average='macro', zero_division=0
    )
    acc = accuracy_score(labels, preds)
    return {"accuracy": acc, "f1": f1, "precision": precision, "recall": recall}

## Step 7: Loading the Pre-trained Model

In [18]:
model = BertForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=NUM_LABELS,
    id2label=ID2LABEL,
    label2id=LABEL_MAP,
)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: dccuchile/bert-base-spanish-wwm-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
bert.pooler.dense.weight                   | MISSING    |
bert.pooler.dense.bias                     | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## Step 8: Configuring Training Arguments

In [19]:
import inspect

# `transformers` has renamed/dropped several TrainingArguments fields across
# versions (e.g. evaluation_strategy -> eval_strategy, and some versions drop
# logging_dir entirely). Filter to whatever this installed version accepts so
# the notebook keeps working across environments instead of erroring on the
# first renamed kwarg.
_desired_training_args = dict(
    output_dir="./results",
    logging_dir="./logs",
    logging_steps=10,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    save_steps=100,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    greater_is_better=True,
    eval_strategy="steps",         # evaluate at regular steps during training
    evaluation_strategy="steps",   # older transformers versions use this name instead
    save_strategy="steps",         # checkpoint at regular steps
    report_to="none",              # disable W&B / external logging
)

_supported_params = set(inspect.signature(TrainingArguments.__init__).parameters)
_dropped = [k for k in _desired_training_args if k not in _supported_params]
if _dropped:
    print(f"Note: this transformers version does not support {_dropped}; skipping them.")

training_args = TrainingArguments(
    **{k: v for k, v in _desired_training_args.items() if k in _supported_params}
)

Note: this transformers version does not support ['logging_dir', 'evaluation_strategy']; skipping them.

## Step 9: Training the Model

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

trainer.train()

C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\epuerta\AppData\Local\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

## Step 10: Final Model Evaluation

In [ ]:
results = trainer.evaluate(eval_dataset=holdout_dataset)
print("Results:", results)

> **Output interpretation:** Shows the final evaluation metrics on the genuine TASS 2018 test set (`tass2018_es_test.csv`), which the model never saw during training or validation. Because this is a 4-class problem (N, NEU, NONE, P), accuracy and F1 here are macro-averaged; expect them to be noticeably lower than a binary positive/negative setup, since the model must also distinguish the harder NEU/NONE classes.